### ISSUE TITLE
ALL connectors - Getting in touch with Chris Holdgraf

### ISSUE THREAD

**Issue by anthonysuen** [data-8/connector-instructors#1]

**Comment by choldgraf** [comment]
hey everybody - in case you'd like get in touch you can ping me on here, or send an email to choldgraf@berkeley.edu

**Comment by SamLau95** [comment]
If it's easier for you @choldgraf it's trivial to set up a Gitter room for this repo for faster response.

**Comment by choldgraf** [comment]
I'll use whatever works best for others.

**Comment by choldgraf** [comment]
Hi @dsten/instructors (esp @cboettig ) - a few people mentioned some confusion about the `Table` object that was created for the course. There's isn't any documentation out there on how to use it, so I wrote a quick reference guide on how to do things with a Table. It's modeled after the "10 minutes to pandas" tutorial, though it doesn't assume anything Pandas-specific.

Link: [10 minutes to tables](https://github.com/choldgraf/write-ups/blob/master/misc/10_min_to_tables.ipynb)

It's still in an incomplete state (in particular, I haven't figured out I/O or pivot tables yet) but should have lots of useful information. It might change if the `datascience` API changes, so feel free to tell me if something breaks or if you think something should be added/changed.

_Note_ - this works using the latest `dev` version of the datascience repository...it may break on earlier versions...

Feel free to ping others about this if they'd be interested

**Comment by SamLau95** [comment]
There is also the datascience API documentation at
http://data8.org/datascience/ — this should be linked to in the README in
the datascience repo but isn't. The tutorial isn't written as of yet but
the reference section is helpful.

**Comment by cboettig** [comment]
@choldgraf @SamLau95 Thanks, this is quite helpful.  

Yes, the official documentation is quite handy too, but it's rather terse.  For instance, `Table.where` is documented as:

```
Table.where(column_or_label, value=None)[source]
Return a Table of rows for which the column is value or a non-zero value.
```

Which could leave some of us a bit confused on the use of inequalities & when to use a column or a label.  Of course this one covered quite nicely in the textbook, but the docs might benefit from some minimal examples showing the different use cases?

**Comment by deculler** [comment]
And there are several tutorial notebooks.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by choldgraf** [comment]
Thanks for the link @SamLau95, I'm going to add it to the top of the `10 minutes` notebook. @cboettig and I spent some time trying to find comprehensive and quick tutorials but couldn't find one, which is why I wrote this. Apologies if it's replicating something else that's out there, but I am more than happy to contribute to the main repository if people find it useful.

**Comment by SamLau95** [comment]
No, this is very helpful — writing a full tutorial is at the top of our
TODO list but no one has taken it on yet.
https://github.com/dsten/datascience/issues/150

**Comment by choldgraf** [comment]
Cool. Well, let me know if there's a way I can change the formatting of this document to either be complimentary to a full tutorial or to contribute material to the tutorial itself.

**Comment by SamLau95** [comment]
If you make changes to the [tutorial.rst](https://github.com/dsten/datascience/blob/master/docs/tutorial.rst) file they'll automatically get pulled onto the online docs when it gets merged into master. You can see https://github.com/dsten/datascience/pull/111/files for a start.

Alternatively, you can keep working on the notebook and I can pull in the text into the file. Let me know what you'd prefer.

**Comment by choldgraf** [comment]
ah ok cool - I'll take a look at the .rst file and see how easy it would be
to transfer over what's there now for a tutorial. Maybe I'll keep
developing the notebook, and then we can decide when it's good enough and
I'll transfer to the text file. Sounds good?

**Comment by SamLau95** [comment]
Yup, great. Thanks!
