### ISSUE TITLE
Creating an instructor FAQ

### ISSUE THREAD

**Issue by choldgraf** [data-8/connector-instructors#10]
This is a place to start compiling a list of Frequently Asked Questions for current and future instructors. Feel free to submit ideas and I'll update the main list in this first post.

**Comment by anthonysuen** [comment]
Chris where are you compiling the FAQ?

**Comment by anthonysuen** [comment]
@choldgraf Curious if it would be published on website or remain on github

**Comment by choldgraf** [comment]
It'll get compiled here, we should add Q/As as they come in, and maybe in a session where we look through previous issues and communications to compile them together. Re: website or github, I'm happy with either. I think it depends on how we decide to store the documentation for this project in general.

**Comment by deculler** [comment]
Github wiki might be good

**Comment by choldgraf** [comment]
Sounds good to me - we can start building up a set of information on the wiki. Just need to make sure that the information that's up there is OK to be public (I believe connector-instructors is a public repo but correct if I'm wrong)

**Comment by choldgraf** [comment]
I've added a section on this to the repository readme, we should add new FAQ questions there
