### ISSUE TITLE
Permissions errors in repos

### ISSUE THREAD

**Issue by choldgraf** [data-8/connector-instructors#12]
Michael Mahoney (not currently a user in this repo so I can't link him) ran into problems after he tried some renaming and moving of files in order to pull fresh copies (see #11). Now he's getting permissions errors and is unable to delete some files in his repository.

@SamLau95 any ideas?

**Comment by SamLau95** [comment]
@choldgraf I think this should be resolved. I'm guessing that him moving files around cause the git checkout to error out without `chown`ing the directories properly. I need to add a catch for that.

**Comment by cboettig** [comment]
Hmm.. doesn't look solved for me?  

e.g. I just used @AndrejGitHub 's link, https://data8.berkeley.edu/hub/interact?repo=history-connector&path=07423-0001-Data.csv, which works great and imports his data file into Jupyter.

Now I cannot actually delete it from my Jupyter environment; I just get a permission denied error.

**Comment by SamLau95** [comment]
Ah, there is in fact a bug. Looking into it now.
ᐧ

On Wed, Jan 20, 2016 at 2:55 PM, Carl Boettiger notifications@github.com
wrote:

> Hmm.. doesn't look solved for me?
> 
> e.g. I just used @AndrejGitHub https://github.com/AndrejGitHub 's link,
> https://data8.berkeley.edu/hub/interact?repo=history-connector&path=07423-0001-Data.csv,
> which works great and imports his data file into Jupyter.
> 
> Now I cannot actually delete it from my Jupyter environment; I just get a
> permission denied error.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/data-8/connector-instructors/issues/12#issuecomment-173390612
> .

## 

Sam Lau
EECS | UC Berkeley | May 2017
(562) 565-4336 | samlau95@berkeley.edu
ᐧ

**Comment by cboettig** [comment]
Note that when a the `interact` link clones a repo, the repo ends up being owned by `root`, not the by the user.  The contents of the repo show up as being owned by the user, but with read only permission, so we cannot delete these files.  Thanks for all the help!

**Comment by SamLau95** [comment]
Yup. The error is in https://github.com/data-8/DS8-Interact/blob/master/app/util.py#L9 since I change the ownership of the file to that of the parent directory (which belongs to root).

**Comment by choldgraf** [comment]
Let me know when this is pulled and I'll let Michael know to give it a shot again...

**Comment by SamLau95** [comment]
It's deployed on both ds8 and data8 I believe. Let me know if he's still
running into issues. I didn't test the sparse-checkout behavior thoroughly
on file moving and renaming so I make no guarantees about behavior at the
moment.
ᐧ

On Wed, Jan 20, 2016 at 6:09 PM, Chris Holdgraf notifications@github.com
wrote:

> Let me know when this is pulled and I'll let Michael know to give it a
> shot again...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/data-8/connector-instructors/issues/12#issuecomment-173428267
> .

## 

Sam Lau
EECS | UC Berkeley | May 2017
(562) 565-4336 | samlau95@berkeley.edu

**Comment by cboettig** [comment]
hmm, just tested on data8 and when I use https://data8.berkeley.edu/hub/interact?repo=health-connector&path=Demo2.ipynb

I get `health-connector` repo added but still owned by root, and I cannot delete either `health-connector` directory or the `Demo2.ipynb` notebook.

**Comment by SamLau95** [comment]
Oops. Looking now.
ᐧ

**Comment by SamLau95** [comment]
Fixed. There were some issues in deploying and I forgot to get around to them.

This and #11 are now closed, so hopefully the interact links will be good to go for us.
