### ISSUE TITLE
403 errors when connector instructors push to their repositories

### ISSUE THREAD

**Issue by choldgraf** [data-8/connector-instructors#14]
Some instructors are running into errors when they try to push to their repositories. After they add their username and password, it's returning a 403 permission denied error. I know this has happened for at least:
_username_ | _connector name_ | _notes_
@mahoneymw | stat89A
@annalauren | ethics-connector | (who also needs to be added to this repo)

Will append new names as they pop up. This will probably be the case for anyone who created a github username within the last few weeks unless they've already been added.

The instructions say to contact you, @SamLau95...can you update their permissions?

**Comment by SamLau95** [comment]
Yup, should be fixed now. I forgot to add the instructors Github team to
the stat89 repo. I made a pass through the other connector repos and it
looks like the instructors team is now added.
ᐧ

On Fri, Jan 22, 2016 at 12:09 PM, Chris Holdgraf notifications@github.com
wrote:

> Some instructors are running into errors when they try to push to their
> repositories. After they add their username and password, it's returning a
> 403 permission denied error. I know this has happened for at least:
> 
> @mahoneymw https://github.com/mahoneymw
> 
> Will append new names as they pop up.
> 
> The instructions say to contact you, @SamLau95
> https://github.com/SamLau95...can you update their permissions?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/data-8/connector-instructors/issues/14.

## 

Sam Lau
EECS | UC Berkeley | May 2017
(562) 565-4336 | samlau95@berkeley.edu

**Comment by choldgraf** [comment]
sounds good, I'll close this unless somebody else complains about it
