### ISSUE TITLE
Clicking interact buttons sometimes clones the whole repository

### ISSUE THREAD

**Issue by choldgraf** [data-8/connector-instructors#15]
A few people mentioned that clicking interact links was copying over whole repositories (or at least whole director structures).

I just tried this myself and wasn't able to replicate the problem (clicking interact with a single file in root director, a single file embedded in a folder, and a single folder). So not really sure whether this is a bug or not, but maybe I missed something.

I'm opening this issue in case the problem comes up again and in case someone else can shed more light on this. Maybe @deculler or @pattyf can share their experience?

**Comment by SamLau95** [comment]
I think this happens when the repo that you're trying to pull either:
1. doesn't have a gh-pages branch, or
2. doesn't have the file/folder you specified on the gh-pages branch.

I can't replicate the issue though, so I can't say for certain.
ᐧ

On Fri, Jan 22, 2016 at 12:25 PM, Chris Holdgraf notifications@github.com
wrote:

> A few people mentioned that clicking interact links was copying over whole
> repositories (or at least whole director structures).
> 
> I just tried this myself and wasn't able to replicate the problem
> (clicking interact with a single file in root director, a single file
> embedded in a folder, and a single folder). So not really sure whether this
> is a bug or not, but maybe I missed something.
> 
> I'm opening this issue in case the problem comes up again and in case
> someone else can shed more light on this. Maybe @deculler
> https://github.com/deculler or @pattyf https://github.com/pattyf can
> share their experience?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/data-8/connector-instructors/issues/15.

## 

Sam Lau
EECS | UC Berkeley | May 2017
(562) 565-4336 | samlau95@berkeley.edu

**Comment by deculler** [comment]
It happens with the readme link in mail earlier to me.  Also the example in
cs-connector/index.html

**Comment by choldgraf** [comment]
hmmm, I just tried going to the cs-connector repo to replicate but it looks
like index.html and the blank.ipynb file have been removed.

**Comment by deculler** [comment]
You are probably on master branch.  They are on gh-pages.

This may be part of the issue.  What branch of the repo does interact pull
from?

On a separate note, is there any reason the autoload is limited to a repo?
Seems like an accessible URL for an ipynb would also be useful to pull into
the environment.

**Comment by choldgraf** [comment]
Ah you're right, I missed that. I just tried clicking the interact button,
and it only pulled the `blank.ipynb` into my repo. It looks like it pulled
from the gh-pages branch (as that's the branch that's active when you do a
`git status` from the command line)

**Comment by deculler** [comment]
I did the test of having the file in master and/or gh-pages.  Either way
you end up with a notebook open on the repo directory rather than the
notebook file.

Is that the intended behavior?  It seems useful in some cases.  But so is
the behavior in the textbook.

**Comment by SamLau95** [comment]
The interact server is configured right now to redirect to the repo root
since that was the easiest thing to do when I implemented the functionality
for the first time. I'll make changes so that the last `path` URL param is
where the user is redirected on a successful pull.

**Comment by SamLau95** [comment]
Looks like this issue is fixed. It was occurring because the interact server assumes `git clone` will clone the `gh-pages` branch. This is true for most connector repos but not in general.

Now it explicitly clones from the `gh-pages` branch so it'll error out for repos without the branch instead of cloning everything.
