### ISSUE TITLE
Students with 503 Proxy Target Missing/500 Internal Server Error

### ISSUE THREAD

**Issue by mads14** [data-8/connector-instructors#18]
Hi,

A few students in the smart cities connector class got errors when trying to use data8.org. There usernames are:

503 Proxy Target Missing:
wangandai 

500 Internal Server Error:
satish.vinay
igormartire

Can you look into these for me and see if you can reset the accounts? In the future is there a way I can fix this myself?

Best,
Maddie (Smart cities connector GSI)

**Comment by SamLau95** [comment]
Pinging @ryanlovett for this. We're looking into these as well as other cases.

Do you have any viable workarounds at the moment?

**Comment by ryanlovett** [comment]
Sorry for the wait. I fixed Satish's earlier in the day. Am looking into
the other two now.

Ryan

**Comment by ryanlovett** [comment]
It seems that the the internal state of the hub can differ from the state
in the db. For example my server was not running anywhere, it did not exist
in the database, but the running jupyterhub process thought it was running.
Supposedly this should not happen
https://github.com/jupyter/jupyterhub/issues/109. I'm restarting the hub
process now which unfortunately temporarily stops the process.

Ryan

**Comment by ryanlovett** [comment]
Unfortunately jupyterhub is failing to start. A jupyterhub commit on 1/20
https://github.com/jupyter/jupyterhub/commit/1a4226419f0ecdceec98c26d8c4525cd3bb04b82#diff-3254677a7917c6c01f55212f86c57fbf
is
incompatible with what we have in our Dockerfile. The jupyterhub builds on
hub.docker.com are untagged
https://github.com/jupyter/docker-stacks/issues/105 so we can't go
backwards. I'm working on forward porting our stuff...

Ryan

**Comment by ryanlovett** [comment]
We are back to where we were before this evenings troubles.

I was able to start igormartire's server without trouble.

wangandai did fail to start. I did the following to get it going:

```
ubuntu@provi1:~$ dssh
ready (28)> docker ps -a | grep wangandai
node23 : 8e335c928e3c        systemuser                                                         "tini -- sh /srv/sin   4 days ago          Exited (1) About a minute ago                             jupyter-wangandai
ready (28)> :quit
ubuntu@provi1:~$ ssh node23
root@node23:~# docker rm jupyter-wangandai
```

**Comment by mads14** [comment]
Thanks for your help! In the future should I create a new issue if anyone has the same 500/503 errors or should I try to restart them myself?

**Comment by ryanlovett** [comment]
Yes, please do both. Create a new issue so that we can track them, but also
attempt to restart them yourself.

Ryan

**Comment by mads14** [comment]
Hey Ryan, now my account (m.sheehan) is giving the server 500 error. I'm not sure that I know how to fix it - I tried briefly to no avail.

**Comment by choldgraf** [comment]
I just looked at the logs and it seems like m.sheehan has a running server. Last seen 18 mins ago. Has this issue been resolved by any chance?

**Comment by mads14** [comment]
Yup, mine is working again. And I haven't had any complaints from students recently, so I think it's all good.

Thanks!
Maddie

**Comment by choldgraf** [comment]
cool! feel free to close the issue whenever you think this is taken care of :)
