### ISSUE TITLE
Private vs Public repos for connector instructors?

### ISSUE THREAD

**Issue by cboettig** [data-8/connector-instructors#2]
@anthonysuen, @papajohn : Do you know if the dsten organization has the capacity to offer private repositories for connector instructors?  Following the strategy of the core course, private repositories seem better suited for making exercises and the like available to other DS8 instructors without tempting students not to do their own work.  

As an intermediate solution, instructors could host their own private repos for that purpose, but it seems more streamlined to have them here, particularly if the goal is to share with instructors while not being public to students.  Again the core course seems to have a very nice set-up where student-facing material goes on the gh-pages branch and becomes public, while assignments remain private on the repo master branch.  Of course, gh-pages might not be amenable to everyone.  

Connector instructors: I'd be curious to hear thoughts of other connector instructors on how you have or plan to manage this aspect.  Would a private repository for the connector be helpful?

**Comment by papajohn** [comment]
Yes, we can set up private repos. If individuals want their own, that's
fine with me, but I'd rather not pre-create one per instructor when most
won't use them. The fewer repos the better.

**Comment by cboettig** [comment]
@papajohn Thanks.  It looks like @anthonysuen has already created a repo for many of the connectors; so I was just wondering if we'd discussed if those were most useful as public or private repos.  

Having not-too-many repos in the org account certainly makes things cleaner.  I suppose connector repos could all be created in a separate org account if that's an option. 

If we are getting lots of connector repos, we might want to have more discussion on naming convention for those repos?  The current names are reasonably semantic but might not scale.  

Apologies if I'm rehashing discussions you've already had about how best to organize this (or if I'm just overthinking things).

**Comment by anthonysuen** [comment]
These are great points @cboettig:

1) I do think by next semester we need to figure out how to deal with the ever growing list of repos. Not sure about the practices since I don't know many universities that runs on our foundational course, connector model. 
2) Perhaps we could just make the all connector repos private? I am not sure having both a private and public repos for one connector make sense.
3) Naming conventions definitely make sense. Could I suggest we start with class titles like ESPM 88 with the complete name to follow? 

Any additional thoughts @choldgraf

**Comment by choldgraf** [comment]
@cboettig can you make a fork of a repo private? I wonder if you could set up public connector repos on the dsten account. Then fork that, make it private, and use PRs to pull in updated content to the main class.

**Comment by choldgraf** [comment]
Alternatively you could just keep it public and assume that students won't go to visit it in general. Can't you look at repository traffic statistics for visits etc? Maybe you can use that to infer whether students are peeking

**Comment by cboettig** [comment]
@anthonysuen My suggestions would be:
1. Name each connector repository with the course number, since those are registered, predictable and unique values that mean something to everyone.
2. Make connector repositories private by default.  
3. If @papajohn & the other dsten foundation core team prefer keeping the dsten github org slim, then we should consider all connectors under a separate connector org.  (Of course, that would break the current import-notebook strategy, because connector gh-pages would no longer be under the data8.org domain name, see https://github.com/dsten/connector-instructors/blob/master/README.md )

@choldgraf @anthonysuen Re public and private, as I mention above there's no need for multiple repositories or forks to have both; we can do what the core course _already does_ with https://github.com/dsten/text : the repo itself private, public information goes on the gh-pages branch where it is published as a public webpage automatically (at http://data8.org/<repo-name>.  Does that make sense?  

(p.s. my course is ESPM 88B, we also have ESPM-88A.  If other departments end up with more than one connector, this may arise again).

**Comment by choldgraf** [comment]
I'm +1 for that to see how it goes. I doubt a ton of instructors will do all of this (at least this first round) so maybe it won't get too cluttered. If this becomes a success story for how to organize the connectors, then perhaps it'll be worth thinking about scaling that upwards at that point.

**Comment by cboettig** [comment]
@choldgraf that makes sense to me to. Right, connector instructors will no doubt continue to do a wide variety of things (bcourses etc), and many might have no use for GitHub repos anyhow. @anthonysuen I think you were intending to create repos for instructors anyhow, if only to create communication channels via issues tracker?  Given that John is wary of having too many repos, maybe that strategy needs further discussion?

**Comment by anthonysuen** [comment]
Sorry for the delay in responding. I think this raises a lot of interesting quetsions. Right now I am actually in the process of setting up connector web pages within the data8.org domain which might make long term migration to a seperate organization more difficult. The goal of the repos are not only for communication, but also to commit code and serve as the web infrastructure for the connector courses.

**Comment by cboettig** [comment]
@anthonysuen I think we can work around the technical stuff if we know what we want, though I agree it makes things more complicated.   

For instance, if John and others really would prefer connectors on a separate org, we can set that org up with CNAME `connector.data8.org`.  But yeah, I agree it's all simpler if connectors stay here but want to make sure we're all happy with that (particularly those having to admin the big picture).

**Comment by SamLau95** [comment]
We're going to go with defaulting to a private repo for connectors, but not until #9 gets implemented.

Until then, we're going to have one private repo and one public repo per connector. (Students pull from the public one.)

**Comment by papajohn** [comment]
We could wait until a connector instructor actually requests a private one
before creating it, just to maintain a bit of order.

**Comment by SamLau95** [comment]
Agreed.
ᐧ

On Tue, Jan 19, 2016 at 9:39 PM, John DeNero notifications@github.com
wrote:

> We could wait until a connector instructor actually requests a private one
> before creating it, just to maintain a bit of order.
> 
> On Tue, Jan 19, 2016 at 9:32 PM, Sam Lau notifications@github.com wrote:
> 
> > We're going to go with defaulting to a private repo for connectors, but
> > not until #9 https://github.com/data-8/connector-instructors/issues/9
> > gets implemented.
> > 
> > Until then, we're going to have one private repo and one public repo per
> > connector. (Students pull from the public one.)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/data-8/connector-instructors/issues/2#issuecomment-173093319
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/data-8/connector-instructors/issues/2#issuecomment-173094031
> .

## 

Sam Lau
EECS | UC Berkeley | May 2017
(562) 565-4336 | samlau95@berkeley.edu

**Comment by cboettig** [comment]
In which case, perhaps the [docs](https://github.com/data-8/connector-instructors/blob/master/README.md) should inform connector instructors that they will need to request a repository before they can follow the rest of the instructions (and specify who the point of contact is for that), otherwise we may have more confusion?

Likewise we should probably add something to the docs telling connector instructors that they will need to request a data8.berkeley.edu account as well?

**Comment by choldgraf** [comment]
That sounds like a good suggestion, FYI I've created an Issue for keeping track of common gotchas / problems / questions. Check out #10 and feel free to add any thoughts.
