### ISSUE TITLE
Links to locations of demo notebooks

### ISSUE THREAD

**Issue by pattyf** [data-8/connector-instructors#20]
Could we add to the instructions for connector instructors the links to example notebooks that we can look to for reference? I know they are in github somewhere and I apologize for not remembering. If there are several good directories to look in then several links please!

**Comment by choldgraf** [comment]
There's a brief mention of this in the Readme file but it's kind of hidden in there. I'll create a more clear section for it. Search for "example notebooks" in the repo. Does what's there look sufficient, or are you thinking of something more?

**Comment by pattyf** [comment]
I found the most helpful notebooks here:
https://github.com/data-8/textbook/tree/gh-pages/notebooks

That link is not under Example Notebooks. Could someone at it?  The
textbook link under Example Notebooks doesn't work (but there is another
link further down on the page).
Thanks! @pattyf

On Fri, Jan 29, 2016 at 11:26 AM, Chris Holdgraf notifications@github.com
wrote:

> There's a brief mention of this in the Readme file but it's kind of hidden
> in there. I'll create a more clear section for it. Search for "example
> notebooks" in the repo. Does what's there look sufficient, or are you
> thinking of something more?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/data-8/connector-instructors/issues/20#issuecomment-176924580
> .

## 

Patty Frontiera
Academic Coordinator
D-Lab, _Supporting Data Intensive Social Science for All_
356 Barrows Hall, University of California Berkeley
http://dlab.berkeley.edu

**Comment by choldgraf** [comment]
Good find @pattyf, I'm swapping out the textbook link with the github link that you just sent, I think that's better as well. Let me know if you think this issue can be closed.

**Comment by pattyf** [comment]
looks great. thanks. i think you can close it.

On Fri, Jan 29, 2016 at 2:29 PM, Chris Holdgraf notifications@github.com
wrote:

> Good find @pattyf https://github.com/pattyf, I'm swapping out the
> textbook link with the github link that you just sent, I think that's
> better as well. Let me know if you think this issue can be closed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/data-8/connector-instructors/issues/20#issuecomment-176998158
> .

## 

Patty Frontiera
Academic Coordinator
D-Lab, _Supporting Data Intensive Social Science for All_
356 Barrows Hall, University of California Berkeley
http://dlab.berkeley.edu

**Comment by choldgraf** [comment]
great!

**Comment by choldgraf** [comment]
(and thanks for your help)
