### ISSUE TITLE
Students getting 503 errors when accessing notebooks

### ISSUE THREAD

**Issue by choldgraf** [data-8/connector-instructors#24]
This was reported by @mahoneymw, who has said that a number of students are getting `503: Proxy target missing` errors. Perhaps @ryanlovett has an idea what might be going wrong?

**Comment by mahoneymw** [comment]
If this is not fixed by Mon AM, then is it possible to have a Plan B.  I teach Mon PM, and I would like to be able to tell the students how to get this---ideally during class, so we can spend some time going over it.

**Comment by choldgraf** [comment]
I'm getting the same errors when using the links that @mahoneymw provided. I also tried another few interact links and I'm also getting the error there. These links return a 503 error for me:

On the stat89a repo:

https://data8.berkeley.edu/hub/interact?repo=stat89a&path=helloword.ipynb

and on another repo:

https://data8.berkeley.edu/hub/interact?repo=health-connector&path=Demo2.ipynb

pinging @SamLau95 and @elaine84 in case there are any updates on this.

**Comment by elaine84** [comment]
@choldgraf @mahoneymw @ryanlovett @SamLau95 actually I can't see anything on data.berkeley.edu though I am logged in with my user account.  I am logged into the course website at data8.org but get the same 503 error when I try to access e.g., https://data8.berkeley.edu/user/elaine/tree or click on any lab notebooks through the main course website

**Comment by choldgraf** [comment]
@SamLau95 mentioned in an email that he has had students run into this problem before as well. Apparently there is some kind of problem with the interact links when the user's server isn't running. His solution was to go to the "Admin" page of his data8 instance, and manually hit "start server" for that user. After that it worked. If the user's session was listed as running, he said to stop, then start it.

I did this for my own account and it worked for me. So maybe that's a sort-of solution. But it's a bit clunky, especially if lots of students run into this problem.

**Comment by ryanlovett** [comment]
Yes, at the moment students need to start their own server before attempting to import files via interact. Documented at https://github.com/data-8/jupyterhub-deploy/issues/12.

One solution is to have interact start the server prior to importing files and redirecting. Another option is to have the hub start the server when it detect that the user's server isn't running.

In the near term, until we address this, could you please have students first start their servers before attempting to click on any interact links? I think we can come up with a way to more transparently start servers however.

**Comment by choldgraf** [comment]
So in debugging this I tried to start my own server the normal way, and it was giving me the same error. The only way I fixed it was by manually starting my server via the admin page. This is the first time that's happened to me, so maybe it's something changed on the backend?

**Comment by elaine84** [comment]
I just had the same problem @choldgraf described -- same error when I click on "Start My Server"

**Comment by choldgraf** [comment]
replication! I feel oddly vindicated...

**Comment by ryanlovett** [comment]
Okay, not great obviously, but a good opportunity to test.

Can you please delete your data8 browser cookies? In Chrome this would be
Settings, type "cookie" in the search field, click Content Settings, Click
All Cookies and Site Data, type "data8" in the search field, then click the
X on the right side of the entry for data8 to delete the browser data.

After doing so, visit data8.berkeley.edu and try starting your server.

Ryan

**Comment by choldgraf** [comment]
I just did all of that and it works fine. But again I was only able to
create this problem one time and haven't been able to re-create it since
then.

**Comment by elaine84** [comment]
I haven't restarted my server through the admin page, and clearing the data8 cookies doesn't seem to work for me.  I've tried variants of this where I log out / log in again and quit / restart my (Chrome) browser.

**Comment by deculler** [comment]
I had to restart server

**Comment by cboettig** [comment]
hmm, I'm getting 500 error from `hub/admin` when I try to start the server for a student who is getting 503 errors.  Any hints or ideas?

**Comment by choldgraf** [comment]
hmm, that sounds like a question for Ryan (cc'ing him here). Not sure if
he's on this list.

**Comment by ryanlovett** [comment]
Here. Can you try deleting any cookies associated with data8.b.e?

I'm going to restart the hub Sunday morning most likely.

Ryan

**Comment by cboettig** [comment]
Thanks. No luck after deleting cookies.  I can start or restart my own session fine but this one student account causes jupyter hub to throw a "500 error API call failed"

**Comment by mads14** [comment]
A few students in the smart-cities connector class are having server issues, and I cannot seem to fix them. 
1. user vvqian is getting 503 error, and I get the "500 error API call failed" when I try to restart her server
2. user lgaytan cannot download new material from git - when she clicks on the link to our demo folder, she gets the message: "error: pathspec 'demos/.ipynb_checkpoints/mini' did not match any file(s) known to git. error: pathspec 'demos/mini did not match any file(s) known to git." If she types the url 'data8.berkeley.edu' her server works, but she is not able to pull new content off git.

Any suggestions for either?
Thanks!
Maddie

**Comment by ryanlovett** [comment]
I see the error with vvqian though I don't understand why it is happening. The hub is trying to start her server in the wrong place -- the hub itself and not the compute nodes. I'll look into it.

What URL is lgaytan clicking on or typing in?

**Comment by mads14** [comment]
Thanks Ryan! 

The url is: https://data8.berkeley.edu/hub/interact?repo=smart-cities-connector&path=demos
It's been working for all the other students.

**Comment by ryanlovett** [comment]
I've fixed vvqian's server. I'll look into the other.

For future infrastructure folks:

root@hub1:~# docker --tls -H tcp://127.0.0.1:2376 rm CONTAINER_ID
where the troublesome ID can be found in the logs, e.g.
Found existing container 'jupyter-USER' (id: CONTAINER_ID)

This doesn't explain why the container's IP remained 0.0.0.0.

**Comment by ryanlovett** [comment]
For lgaytan, I renamed "demos" in smart-cities-connector to "demos.bak". Please have her attempt to refetch the content. If she needs to look at files she previously modified, they can be found in the demos.bak directory.

**Comment by mads14** [comment]
@ryanlovett, I just messaged vvqian to let her know it is working. I just got an email back from her that says: "Thank you! Although it did connect for around 2 minutes, the error (500: Internal Server Error) persists"

I am again not able to reset her server. Sorry! And thanks for your help.

**Comment by mads14** [comment]
Thanks! Should lgaytan try the link https://data8.berkeley.edu/hub/interact?repo=smart-cities-connector&path=demos.bak, then?

**Comment by ryanlovett** [comment]
No, she should try the regular link to demos which should pull a fresh copy of the directory. Please let me know if that does not work.

Regarding vvqian, so it was working for two minutes but then failed somehow? I started her container via the admin console and have left it running. Can you have her try again?

**Comment by mads14** [comment]
Thanks! I will report back, when I hear from the students.

**Comment by deculler** [comment]
Thanks all for digging into this.  It's a learning curve process.

Part of the trick is that it is hard to capture the fault.  For example,
just trying things now

https://data8.berkeley.edu/user/culler/notebooks/cs-connector/Lec03-Review.ipynb

gave me a page containing only /hub/home but on a second click after
opening another notebook gave me the proper result.  Over the weekend I was
consistently getting 502 errors.  I figured it was about being off campus,
but then is vanished.  The cloud is a tricky little beast and we are
pushing the envelope pretty hard.  So thanks again.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by ryanlovett** [comment]
I just created [an issue](https://github.com/data-8/jupyterhub-deploy/issues/17) for adding some sort of log monitoring to the deployment.

data8 was offline ~10a-3p Sunday due to issues that prolonged hub restart, including an ORM db error, a faulty node, and a zombie docker process on the provisioner. I plan on restarting the hub this Sunday morning so I can bring up the restuser container. I'll broadcast to the instructors later in the week.

**Comment by mads14** [comment]
Hi again. I can't access my account right now (m.sheehan). It gives a 503 error, but when I try to restart the server from the admin page it gives a 400 server already running error.

Also another student, ralexander, reported an issue similar to the one that lgaytan saw. He get's a message "error: pathspec 'demos/Minilab3' did not match any file(s) known to git." when he tries to access the https://data8.berkeley.edu/hub/interact?repo=smart-cities-connector&path=demos link

Also, is this the best way for me to report issues with user accounts?

**Comment by mads14** [comment]
Mine's back - not sure if you just fixed it, but thanks!

**Comment by ryanlovett** [comment]
Yes, I fixed it and was going to try starting your server but I saw it was already running.

Someone else had a similar pathspec issue. The workaround there was to backup the demos folder had have the student refetch the files. If ralexander had modified files they could be copied from the backup folder. I'll rename it to demos.bak.

**Comment by mads14** [comment]
Hi @ryanlovett, Could you reset annie_wong's account. Restarting her server from the admin page isn't working. Thanks!

**Comment by mads14** [comment]
Sorry the username is annie_wang.

**Comment by ryanlovett** [comment]
Done!

**Comment by mads14** [comment]
Thanks! Another request. Can you do the demos.bak fix that you did for a few others for alexeip. He's getting the path issue that others have been getting.

Thanks!

**Comment by ryanlovett** [comment]
Done. The student can do this in a jupyter terminal via:
`cd ~/smart-cities-connector && mv demos demos.bak`
This means: go to the smart-cities-connector directory and rename "demos" to "demos.bak".

**Comment by mads14** [comment]
@ryanlovett - can you please reset alexeip's account. It is giving the 500: server error, and I cannot reset it from the admin panel.

Thanks!
Maddie

**Comment by ryanlovett** [comment]
Fixed!

**Comment by mads14** [comment]
Hey @ryanlovett  - fhoang7 is getting error 504 - server timeout and I am not able to reset it. Could you try?

Thanks!

**Comment by ryanlovett** [comment]
ds8 or data8?

**Comment by mads14** [comment]
data8

**Comment by ryanlovett** [comment]
I just reset it. It was running so I stopped, started, then stopped again.

**Comment by mads14** [comment]
Great! Thank you! I had tried the same, but it didn't work for me. I also got a timeout error.

**Comment by mads14** [comment]
@ryanlovett, could you reset talitha.mcadams account when you get a chance? Thanks!

**Comment by ryanlovett** [comment]
Done!

**Comment by mads14** [comment]
Thanks! Sorry for all the requests - can you reset my account: m.sheehan. I'm locked out and cannot reset it from the admin.

**Comment by ryanlovett** [comment]
Fixed. The error you were seeing should have been fixed a couple of weeks ago. I'll investigate.

**Comment by ryanlovett** [comment]
The source of all of these issues was fixed by jupyterhub 0.5. It was a race condition exacerbated by the different conditions at azure. data8 now has 0.5 and we will upgrade ds8 at the end of the semester.

**Comment by deculler** [comment]
David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

---------- Forwarded message ----------
From: David CULLER <culler@berkeley.edu>
Date: Tue, Apr 19, 2016 at 7:04 AM
Subject: Fwd: Data bears logo
To: Cathryn CARSON <clcarson@berkeley.edu>, Ani ADHIKARI <
adhikari@berkeley.edu>, WAI HUNG SUEN <anthonysuen@berkeley.edu>, "Michael
I. JORDAN" <michael_jordan@berkeley.edu>, John DeNero <denero@berkeley.edu>,
David Wagner <daw@berkeley.edu>



David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

---------- Forwarded message ----------
From: Elizabeth Kim <kim.soohyun@steelcode.com>
Date: Tue, Apr 19, 2016 at 6:53 AM
Subject: Re: Data bears logo
To: David CULLER <culler@berkeley.edu>


These are both .png files at about 2800x2800.
I couldn't find a higher resolution for Oski's face and I tried to clean
him up a bit but I could do more if needed!


On Mon, Apr 18, 2016 at 7:31 AM, David CULLER <culler@berkeley.edu> wrote:

>
> Images can either be JPG or PNG, PNG if there are some transparent areas.
> From experience, you should allow for the white border around the image.
> They really don't mention it in the instructions but if the image rides up
> agains the size limits, the image will be cropped since the border will
> always be there.
>
>
>    - 600x800 pixels for small size
>    - 1100x1100 pixels for medium size
>    - 1700x1700 pixels for large size
>    - 2800x2800 pixels for X-Large size
>    - The file must be a PNG for transparencies to be saved. We recommend
>    uploading a file with the maximum pixel requirements (2800 x 2800px) to
>    ensure your design is available on all 4 sticker sizes
>
>
>
> If you would like more information about the image size limitations for
> the various products they sell on their site, here is the link:
>
>
> https://help.redbubble.com/hc/en-us/articles/202270679-Dimensions-Format-and-Colour
>
> David E. Culler
> Friesen Professor of Computer Science
> Electrical Engineering and Computer Sciences
> University of California, Berkeley
>
> On Mon, Apr 18, 2016 at 4:30 PM, David CULLER <culler@berkeley.edu> wrote:
>
>> I suppose that you could move the words up a tiny bit, move them slightly
>> closer together, and possibly a tiny bit larger.  It will be a little
>> ambiguous if it is one word or two.  That's good.
>>
>> David E. Culler
>> Friesen Professor of Computer Science
>> Electrical Engineering and Computer Sciences
>> University of California, Berkeley
>>
>> On Mon, Apr 18, 2016 at 10:50 AM, Elizabeth Kim <
>> kim.soohyun@steelcode.com> wrote:
>>
>>> Hi,
>>>
>>> This is Elizabeth, the work study student from 410.
>>> Here's a design I have so far for the databears sticker you asked for.
>>> I was hoping to have 2 or 3 for you to choose from but I'm not sure what
>>> exactly you're looking for.
>>>
>>> Perhaps you can take a look at this and let me know what you like/don't
>>> like.
>>> Also, what file format do you need to make stickers?
>>>
>>> Regards,
>>> Elizabeth
>>>
>>
>>
>


-- 
Email: skim@steelcode.com
Phone: (619)746-0836
