### ISSUE TITLE
Enable recursive folder removal

### ISSUE THREAD

**Issue by anthonysuen** [data-8/connector-instructors#25]
One use case is that I might want to remove rather than rename it and then re-download the lab folder.  I.e., a different use case people might want is if they mess up a notebook is to remove it and then reclick on the link via the main class page to get a new notebook.  But, right now, you from the interface you can't remove a non-empty folder.  If I go two levels down into the directory hierarchy, remove files, then work my way back up, removing empty folder, I can remove the main folder.  But that is pretty inconvenient.  So, that may be okay, but it will make things difficult for some people.  

(In Unix, this corresponds to "rmdir directory.name" rather than "rm -r directory.name", so it's probably an easy fix, but some people might get anxious about that much power.  I personally would prefer that change, and I think that students in most of the technical connectors would.  I don't know whether the less technical connectors would like the added insurance of not removing non-empty folders, so it might be worth asking them that.)

Thanks,

**Comment by SamLau95** [comment]
This is a restriction that Jupyterhub itself puts in, I believe. Might be
more difficult to implement this without someone familiar with the Jupyter
code.
ᐧ

On Wed, Feb 3, 2016 at 12:00 PM, anthonysuen notifications@github.com
wrote:

> One use case is that I might want to remove rather than rename it and then
> re-download the lab folder. I.e., a different use case people might want is
> if they mess up a notebook is to remove it and then reclick on the link via
> the main class page to get a new notebook. But, right now, you from the
> interface you can't remove a non-empty folder. If I go two levels down into
> the directory hierarchy, remove files, then work my way back up, removing
> empty folder, I can remove the main folder. But that is pretty
> inconvenient. So, that may be okay, but it will make things difficult for
> some people.
> 
> (In Unix, this corresponds to "rmdir directory.name" rather than "rm -r
> directory.name", so it's probably an easy fix, but some people might get
> anxious about that much power. I personally would prefer that change, and I
> think that students in most of the technical connectors would. I don't know
> whether the less technical connectors would like the added insurance of not
> removing non-empty folders, so it might be worth asking them that.)
> 
> Thanks,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/data-8/connector-instructors/issues/25.

## 

Sam Lau
EECS | UC Berkeley | May 2017
(562) 565-4336 | samlau95@berkeley.edu

**Comment by ryanlovett** [comment]
I believe that is actually a limitation in Jupyter's ContentsManager. I agree, that behavior is annoying.

Some starting points:
https://github.com/jupyter/notebook/blob/master/docs/source/extending/contents.rst
https://github.com/jupyter/notebook/blob/master/notebook/static/services/contents.js

**Comment by choldgraf** [comment]
This issue seems to be better in a different data 8 repository than this one. Mind if I close it so it can be opened elsewhere?
