### ISSUE TITLE
Please install Shapely and Pyproj libraries for geospatial connector

### ISSUE THREAD

**Issue by pattyf** [data-8/connector-instructors#27]
@ryanlovett Please install the shapely and pyproj libraries. See attached notebooks as examples of use. I would like to use these in 2 weeks. 

[shapely_pyproj_notebooks.zip](https://github.com/data-8/connector-instructors/files/133633/shapely_pyproj_notebooks.zip)

Thanks much.

**Comment by ryanlovett** [comment]
This was done a while back and communicated to Patty. Forgot to close.

**Comment by pattyf** [comment]
And I forgot to say thank you!
- Patty

On Thu, Mar 10, 2016 at 3:54 PM, Ryan Lovett notifications@github.com
wrote:

> This was done a while back. Forgot to close.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/data-8/connector-instructors/issues/27#issuecomment-195107276
> .

## 

Patty Frontiera
Academic Coordinator
D-Lab, _Supporting Data Intensive Social Science for All_
356 Barrows Hall, University of California Berkeley
http://dlab.berkeley.edu

**Comment by ryanlovett** [comment]
No problem. :)
