### ISSUE TITLE
add a postgresql python module (psycopg2?) to data8 server?

### ISSUE THREAD

**Issue by cboettig** [data-8/connector-instructors#28]
Could we get a postgresql module added to the servers?  `psycopg2` seems to be what comes up when I google but I'm open to suggestions (still thrilled with @ryanlovett 's suggestion to use `requests` instead of `urllib`/`urllib2`)

It's not essential as I'm not actually teaching SQL queries and can always extract the data into `csv`s beforehand for students, but I prefer to at least illustrate where data originally comes from to try and demystify this a bit.  Thanks.

**Comment by ryanlovett** [comment]
If you want to demonstrate making a connection to a database then sqlite3 would be easiest. If you want to really connect to a remote database then you'll need the postgres or mysql modules. Python [abstracts](https://www.python.org/dev/peps/pep-0249/) database connections so theoretically the API should be the same for local or remote dbs.

**Comment by cboettig** [comment]
thanks, yeah this data is already available in postgresql format so it would be nice to use that module.

**Comment by ryanlovett** [comment]
Okay, will look into it.

**Comment by ryanlovett** [comment]
I've installed it on data8. If it looks okay to you I'll push it to ds8 as well. Remember to stop/start your server.

**Comment by ryanlovett** [comment]
I just remembered that there may be firewall restrictions (possibly egress) associated with Azure. I'll take a look tomorrow.

**Comment by choldgraf** [comment]
This issue seems to be more appropriate in a different data8 repo. Mind if I close it so that it can be discussed there?
