### ISSUE TITLE
Please install pysal library

### ISSUE THREAD

**Issue by pattyf** [data-8/connector-instructors#29]
Hi @ryanlovett,
Pysal (python spatial analysis library) is now available for python 3. Could you please install it on data8/ds8 jupyter servers?  We likely won't use it for a class exercise but I would like to demo it. If you can't get to it that is fine, I can plan for a future semester.  Thanks! Patty

**Comment by ryanlovett** [comment]
Done, version 1.11.1.

**Comment by pattyf** [comment]
@ryan thanks so much! super fast of you.
