### ISSUE TITLE
How do students submit (jupyter notebook) assignments?

### ISSUE THREAD

**Issue by cboettig** [data-8/connector-instructors#3]
What is the proposed workflow for students to submit Jupyter Notebooks?  (It's not actually clear to me how to download a notebook from https://ds8.berkeley.edu and email it; so far I've relied on git to move work off https://ds8.berkeley.edu).  

I think the ideal might for instructors to be able to log in to https://ds8.berkeley.edu _as an instructor_ and thus see their working directory be populated with the subdirectories for each student in the course. (Currently it appears that instructor logins are functionally the same as a student login; we can see our own work but not that of our students).

**Comment by ryanlovett** [comment]
Hi Carl,

Fall used the "ok" autograder. There's some info here:
- http://data8.org/resources.html
- https://pypi.python.org/pypi/okpy
- https://github.com/Cal-CS-61A-Staff/ok/
- https://okpy.org

It integrates with ds8
https://github.com/dsten/jupyterhub-deploy/blob/master/roles/singleuser/files/Dockerfile#L23-L28
via
a notebook extension https://github.com/dsten/notebook-ok-extension. John
et al created okpy.

Ryan

**Comment by cboettig** [comment]
Thanks Ryan!  However I don't think any _connectors_ use the automatic
grader; my impression is that most connector instructors don't need that
scale (being <= 30 students mostly), and besides would be more focused on
the kinds of questions that cannot be graded that way (after all, the
foundation course is doing most of the teaching of the python coding for
us).

So I still think we need a viable mechanism for connector instructors to
view student notebooks directly (preferably with a workflow that also
supports an explicit "submission" step) but doesn't involve the overhead of
the autograder setup.

**Comment by ryanlovett** [comment]
There is currently only one way of doing so which is to SSH to the jupyterhub host directly. GSIs used that method to push out assignments.

User kernels only have access to ~/ within the Hub environment so instructors' single user servers can't see anyone else's home data. From an instructor's perspective, I can see that it would desirable to browse through students' homes, the same way one does with one's own home dir, to select and view notebooks. Is there another method you have in mind?

> So I still think we need a viable mechanism for connector instructors to view student notebooks directly (preferably with a workflow that also supports an explicit "submission" step)

So you're thinking that an instructor would view students' notebooks, then mark them up with notes and grades, and then commit them to something? Or view, commit, and grade out-of-band?

**Comment by cboettig** [comment]
@ryanlovett Right, and having connector instructors ssh in sounds really messy/risky. My thinking was that an admin person (or script) running on the host would automatically copy the working directories of all users in a connector into subdirectories of that connector's instructor.  (Ideally the instructor would also then have a "student" account, as @deculler suggested, so they can see what students see).  An instructor could then grade each notebook 'manually', either marking it up directly or keeping grading / feedback in some other format.  The key here is just that it is easy to run the student's code in the same environment.  

Such a strategy would be workable, but maybe a bit too 'rough and ready' to be ideal.  Like you say, it doesn't cover how to get the graded/marked up version back to the students, and copying whole user directories is clunky.  @deculler mentioned that most CS classes do this with a complete Git/Github workflow now, which is in many ways ideal, but is perhaps too technical for DS-8?  I'd love to hear thoughts from David and others who have experience in doing that.  Maybe there's a lightweight way to script around that doesn't assume both student and instructor are knowledgable about git?

**Comment by anthonysuen** [comment]
@cboettig Thanks for question! I think we should clearly document the workflow for the other connectors who are still trying to figure things out. Would be happy to write up something. I believe Yang Xu's cognitive science course is interested in using an autograde, but I am not sure he is aware of the solution employed in DS8.

**Comment by SamLau95** [comment]
@cboettig I think the easiest way is to have students export their completed notebooks as a PDF file which they can then submit to your bCourses (a Dropbox might also work).

This requires no extra setup on your part except to teach students how to submit. bCourses also has a PDF annotating system you can use to mark assignments although it's unintuitive to use.

We're having students export labs and homeworks as HTML files for Data 8. Right now we don't have automatic ok.py submissions either.

**Comment by cboettig** [comment]
Great suggestion, I'll give that a try.  Think we can close this since it's now in the connector docs as well.
