### ISSUE TITLE
Removing website materials from connector-instructors master branch

### ISSUE THREAD

**Issue by choldgraf** [data-8/connector-instructors#35]
I see there is also a gh-pages branch in the conncetor-instructors repo. I assume that's hosting the website content. @anthonysuen is it OK if I delete all the CSS, `index.html` etc pages from the master branch?

**Comment by anthonysuen** [comment]
Yep feel free to do so. Where would be put all the information in the future. The wiki?

**Comment by choldgraf** [comment]
it should still be in the `gh-pages` branch...the master branch isn't used for the website anyway.
