### ISSUE TITLE
Add links section to Wiki

### ISSUE THREAD

**Issue by pattyf** [data-8/connector-instructors#43]
I would find it helpful to have a links section in the Wiki side menu. There are lots of URLs within the Wiki pages but would be good to have quick reference.

Also, I would add a reference to the datascience package documentation (http://data8.org/datascience/) in the Course Software wiki.

**Comment by choldgraf** [comment]
@gunjanbaid is this something you can address w/ Patty?

**Comment by gunjanbaid** [comment]
I can definitely add these things in! I'll have both of those changes added by the end of today.

**Comment by gunjanbaid** [comment]
Both changes have been made! Links [here](https://github.com/data-8/connector-instructors/wiki/Links) and datascience documentation [here](https://github.com/data-8/connector-instructors/wiki/Software-Resources) (towards the end of the page). I'll keep adding to the links page.
