### ISSUE TITLE
Make data8.org/connector-instructors redirect to the wiki

### ISSUE THREAD

**Issue by choldgraf** [data-8/connector-instructors#45]
Hey all - since the wiki is the main source of information and landing page for the connectors, can we make:

`http://data8.org/connector-instructors/`

redirect to:

`https://github.com/data-8/connector-instructors/wiki`

?

This will also allow instructors to get the repository by using an interact link.

**Comment by choldgraf** [comment]
maybe @SamLau95 or @anthonysuen know how to do this

**Comment by SamLau95** [comment]
Yeah, you'll want to stick an `index.html` in the root of the `gh-pages` branch, then have that HTML page make the redirect. http://stackoverflow.com/questions/5411538/redirect-from-an-html-page

**Comment by choldgraf** [comment]
using `meta` for the redirect was causing it to go into a loop, so I've just made the readme a little clearer and will use that as a landing page. People can go from there.
