### ISSUE TITLE
Add `nbgrader` as a default package in the cluster

### ISSUE THREAD

**Issue by choldgraf** [data-8/connector-instructors#46]
hey @ryanlovett can we add `nbgrader` to the docker image for the cluster? That way connector instructors can use the `connectortools` module on datahub.

**Comment by choldgraf** [comment]
also note that this should should be whatever is in the latest master, not necessarily on `pip`, depending on when that was last updated

**Comment by choldgraf** [comment]
for now I added a pip install to the `index.ipynb` notebook, which should work OK

**Comment by ryanlovett** [comment]
Regarding:
> also note that this should should be whatever is in the latest master, not necessarily on pip, depending on when that was last updated

Would it be sufficient for us to use nbgrader's latest commit hash? We want to avoid underspecifying versions since that isn't reproducible.

**Comment by choldgraf** [comment]
actually I just tried pip-installing and that worked fine, so that works

**Comment by choldgraf** [comment]
I'll close this for now, since most instructors should be able to figure it out from the index.ipynb notebook...but LMK when you're able to get nbgrader on the cluster so I can remove that code

**Comment by ryanlovett** [comment]
https://github.com/data-8/jupyterhub-k8s/commit/48034b24990402f20f47534f8019202291643c4a

Will post when it is pushed to cluster.

**Comment by choldgraf** [comment]
+1
