### ISSUE TITLE
https://data8.berkeley.edu/ returns a 403 error

### ISSUE THREAD

**Issue by pattyf** [data-8/connector-instructors#6]
I'm following the directions for connector instructors for creating a new jupyter notebook and the url
https://data8.berkeley.edu/ returns a 403 error page.

**Comment by choldgraf** [comment]
I believe this might be a problem with adding new users to the new data8 vs. the old ds8. What's your berkeley.edu address and I'll try to add you

**Comment by SamLau95** [comment]
Everyone was running into this earlier today; we think we've fixed it. @pattyf can you confirm that you can log in?

**Comment by choldgraf** [comment]
If it was a 4xx error there's a chance it was still just a missing username, no? The server problem was a 5xx error

**Comment by SamLau95** [comment]
Ah, you're right. I just added you to the system @pattyf . Sorry 'bout that.

**Comment by pattyf** [comment]
Yes, I can see it. Thanks much.
