### ISSUE TITLE
Add more instructions about creating notebooks to Getting Started as a connector instructor doc.

### ISSUE THREAD

**Issue by pattyf** [data-8/connector-instructors#7]
I don't think the instructions for notebooks addresses the following:
1) how to upload data with a new notebook

2) this workflow: clone notebook > edit repo locally > merge changes to master > merge changes to gh-pages. When I tried this I get the following:

dlab-patty:geospatial_connector2 patty$ git push origin gh-pages
ERROR: Permission to data-8/geospatial-connector.git denied to pattyf.
fatal: Could not read from remote repository.

**Comment by SamLau95** [comment]
You're right about 1. I'll add a note.

For 2, you have to accept your Github invitation to join the `data-8` org. It looks like your invitation is still pending. You can try poking around here or looking through your email for something from Github.
