### ISSUE TITLE
Instructions for adding and testing new python modules needed

### ISSUE THREAD

**Issue by pattyf** [data-8/connector-instructors#8]
If I submit a new notebook for my connector and it has one or more modules that are not used by the foundation course I need to know if/when these get installed so that I can test my notebook on the remote hub.  I cannot use the jupyter notebook hub environment if I cannot get these modules installed  a week before I distribute an assignment so that I can test it. What is the process for ensuring this? Should I upload the notebook and then add a new issue to install any needed modules? If you could add some info on this to the documentation that would be great.

**Comment by ryanlovett** [comment]
In terms of procedure and policy I'll defer to @papajohn.

But I think it would be good to create a new issue and attach your notebook to it. We'll try to integrate any additional libraries that your notebook specifies. The more lead time we have the better.

When we do update the single user server with new software, it requires that students stop and start their server.

**Comment by papajohn** [comment]
I like Ryan's plan of creating an issue. Ryan will be the central point of
contact for adding new modules.

**Comment by choldgraf** [comment]
Hey all - is Ryan's response going to be the party line on how to deal with adding new modules? If so I can add it to the Readme and then I'll close this...

**Comment by ryanlovett** [comment]
Yes, thanks Chris.

**Comment by choldgraf** [comment]
OK, added this to the readme in the FAQ section
