### ISSUE TITLE
`interact` mechanism should support private repositories

### ISSUE THREAD

**Issue by cboettig** [data-8/connector-instructors#9]
The idea here is based on discussion with @SamLau95 in gitter.

It would be nice to have a mechanism by which connector instructors can distribute notebooks & data to the Jupyter servers without it being public.  

The current workflow outlined in this repo to use the `interact` URLs assumes that the repository is public, and also assumes that it should clone the branch named `gh-pages`, even though this isn't explicitly documented.  Seems like assuming the branch is `gh-pages` creates another point of failure?  A connector instructor just trying to distribute content in this way has no need of the HTML functions of `gh-pages`, and @anthonysuen 's team is already putting website information on all the `gh-pages` branches.  

Sam suggested it would be possible to make sure the server has the credentials required to import from private repositories on data-8.org.  

Related to this issue: On the mailing lists, @pattyf brought up the question asking for recommendations on how connector instructors manage both public content for students & private content like answer keys.  @papajohn suggested having two separate repositories on data-8 to address this; one for public and one for private copies.

**Comment by SamLau95** [comment]
This functionality will be enabled soon; I'm pushing to the servers tonight. Then, you can gives students links for private repos that will pull from the `gh-pages` branch.

**Comment by SamLau95** [comment]
This is now pushed to ds8 and data8. You may use private repos as well as public ones when constructing interact links. As usual, the `gh-pages` branch is the one that needs to have the files you want to give out.

For example, for the `ecology-connector` repo, you can give students a link that looks like:

```
https://data8.berkeley.edu/hub/interact/?repo=ecology-connector&path=README.md
```
